# Generated by Django 6.0.5 on 2026-07-04 13:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=150)),
                ('model', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(choices=[('panel', 'Solar Panel'), ('battery', 'Battery'), ('inverter', 'Inverter'), ('controller', 'Charge Controller'), ('breaker', 'Breaker'), ('cable', 'Cable'), ('mounting', 'Mounting'), ('connector', 'Connector'), ('accessory', 'Accessory')], max_length=30)),
                ('rating', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('unit', models.CharField(default='pcs', max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='components/')),
                ('datasheet', models.FileField(blank=True, null=True, upload_to='datasheets/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('minimum_stock', models.PositiveIntegerField(default=5)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'brand', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('customer', 'Customer')], default='customer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SolarProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(max_length=30, unique=True)),
                ('client_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('system_type', models.CharField(choices=[('offgrid', 'Off Grid'), ('hybrid', 'Hybrid'), ('ongrid', 'On Grid')], default='hybrid', max_length=20)),
                ('roof_type', models.CharField(choices=[('flat', 'Flat'), ('pitched', 'Pitched'), ('metal', 'Metal')], default='pitched', max_length=20)),
                ('roof_area', models.FloatField(default=0)),
                ('roof_tilt', models.PositiveIntegerField(default=20)),
                ('roof_orientation', models.CharField(default='South', max_length=50)),
                ('sun_hours', models.FloatField(default=5)),
                ('system_voltage', models.PositiveIntegerField(default=24)),
                ('battery_autonomy', models.PositiveIntegerField(default=1)),
                ('system_losses', models.FloatField(default=20)),
                ('design_factor', models.FloatField(default=1.2)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('design', 'Designing'), ('quoted', 'Quoted'), ('approved', 'Approved'), ('installed', 'Installed'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SolarCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_daily_load', models.FloatField(default=0)),
                ('total_peak_load', models.FloatField(default=0)),
                ('total_ac_load', models.FloatField(default=0)),
                ('total_dc_load', models.FloatField(default=0)),
                ('panel_wattage', models.PositiveIntegerField(default=550)),
                ('required_panel_watts', models.FloatField(default=0)),
                ('required_panels', models.PositiveIntegerField(default=0)),
                ('panel_strings', models.PositiveIntegerField(default=0)),
                ('battery_voltage', models.PositiveIntegerField(default=12)),
                ('battery_capacity', models.FloatField(default=0)),
                ('battery_quantity', models.PositiveIntegerField(default=0)),
                ('inverter_size', models.FloatField(default=0)),
                ('inverter_quantity', models.PositiveIntegerField(default=1)),
                ('controller_size', models.FloatField(default=0)),
                ('controller_quantity', models.PositiveIntegerField(default=1)),
                ('breaker_size', models.FloatField(default=0)),
                ('cable_size', models.CharField(blank=True, max_length=50)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculation', to='solarnaija.solarproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('design', 'System Design'), ('quotation', 'Quotation'), ('proposal', 'Proposal'), ('bom', 'Bill of Materials')], max_length=20)),
                ('file', models.FileField(upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='solarnaija.solarproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('labour_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('logistics_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('installation_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('miscellaneous_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_percentage', models.FloatField(default=0)),
                ('markup_percentage', models.FloatField(default=15)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('validity_days', models.PositiveIntegerField(default=30)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='solarnaija.solarproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executive_summary', models.TextField(blank=True)),
                ('scope_of_work', models.TextField(blank=True)),
                ('warranty', models.TextField(blank=True)),
                ('installation_duration', models.CharField(default='3-5 Working Days', max_length=100)),
                ('payment_terms', models.TextField(blank=True)),
                ('exclusions', models.TextField(blank=True)),
                ('validity_days', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('sent', 'Sent'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='solarnaija.quote')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='solarnaija.solarproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file_type', models.CharField(choices=[('drawing', 'Drawing'), ('quotation', 'Quotation'), ('proposal', 'Proposal'), ('invoice', 'Invoice'), ('contract', 'Contract'), ('photo', 'Photo'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(upload_to='project_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='solarnaija.solarproject')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created Project'), ('updated', 'Updated Project'), ('design', 'Generated Design'), ('quote', 'Generated Quote'), ('proposal', 'Generated Proposal'), ('file', 'Uploaded File'), ('deleted', 'Deleted Item')], max_length=30)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='solarnaija.solarproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('lighting', 'Lighting'), ('cooling', 'Cooling'), ('kitchen', 'Kitchen'), ('office', 'Office'), ('entertainment', 'Entertainment'), ('industrial', 'Industrial'), ('pump', 'Water Pump'), ('security', 'Security'), ('other', 'Other')], default='other', max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('watts', models.FloatField()),
                ('surge_watts', models.FloatField(default=0)),
                ('hours_per_day', models.FloatField()),
                ('days_per_week', models.PositiveIntegerField(default=7)),
                ('power_factor', models.FloatField(default=1.0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliances', to='solarnaija.solarproject')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
